services:
  app:
    container_name: url-shortener
    environment:
      - DB_HOST=postgres
      - DB_NAME=url
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - api:/app/
    depends_on:
      - postgres          # Uncomment this when using postgres.
    networks:
      - url-shortener

  postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=url
      - DATABASE_HOST=postgres
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - url-shortener
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  api:
  database_postgres:

networks:
  url-shortener:
    driver: bridge
